config/routes.rb
Rails.application.routes.draw do
  root to: "lists#index"
  resources :lists, except: [:destroy] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie_id, uniqueness: { scope: :list_id, message: "Le couple movie et list doit être unique" }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks, dependent: :destroy

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @movie = Movie.find(params[:bookmark][:movie_id])
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  def update
    @bookmark = Bookmark.find(params[:id])
    @bookmark.update(bookmark_params)
    if @bookmark.save
      redirect_to list_path(@bookmark.list)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    # raise
    @bookmark = Bookmark.find_by(movie_id: params[:id])
    @bookmark.destroy

    @list = List.find(params[:list])
    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    # Récupération de la liste de films via Bookmarks
    @movies = @list.movies
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to lists_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/edit.html.erb
<div class="container">
  <h1>Modify your comment</h1>

  <%= simple_form_for @bookmark do |f| %>
    <%= f.association :movie %>
    <%= f.input :comment %>
    <%= f.submit "Update #{@bookmark.list.name}"%>
  <% end %>
</div>

app/views/bookmarks/new.html.erb
<div class="container">
  <h1>Add a movie to the list</h1>

  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie %>
    <%= f.input :comment %>
    <%= f.submit "Add to #{@list.name}"%>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="navbar-watch align-items-center">

      <%= link_to lists_path, class: "d-flex justify-items-center" do %>
        <%= image_tag('popcorn_logo.png', alt: 'Watchlist logo', size: '60x60') %>
      <% end %>

      <div class="d-flex me-3">
        <%= link_to "My lists", lists_path, class: "me-3" %>
        <%= link_to "New list", new_list_path %>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit %>
  <% end %>

app/views/lists/index.html.erb
<div class="banner">
  <h1>Save any kind of movies</h1>
</div>

<div class="container">
  <div class="d-flex justify-content-between mt-5 align-items-center">
    <h2>My lists</h2>
    <%= link_to "Create a movie list", new_list_path, class:"button-add" %>
  </div>

  <ul class="container-lists">
    <% @lists.each do |list| %>
      <%= link_to list_path(list) do %>
        <li>
          <div class="my-card card-list" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.photo.attached? ? cl_image_path(list.photo.key, width: 1000, height: 500 ,crop: :thumb, gravity: :face) : asset_path('cinema.jpg') %>)">
            <%= list.name %>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h1>New list</h1>

  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: url(<%= @list.photo.attached? ? cl_image_path(@list.photo.key, width: 1000, height: 500 ,crop: :thumb, gravity: :face ) : asset_path('cinema.jpg') %>)" >
  <h1><%= @list.name %></h1>
</div>

<div class="container">
  <div class="d-flex justify-content-between mt-5 align-items-center">
    <h1><%= @list.name %>'s list</h1>
    <%= link_to "Modify list", edit_list_path(@list) %>
    <%= link_to "Add a movie", new_list_bookmark_path(@list), class: "button-add" %>
  </div>

  <%# // Montrer tous les films associés  %>
  <ul class="container-movies">
    <% @movies.each do |movie| %>
      <li class="my-card">
        <div class="card-movie">
          <div>
            <%# the image stored in poster_url is a predefined poster made by TMDB.
            Change seed to get the whole movie poster %>
            <%= image_tag(movie.poster_url, class: "card-movie-picture", width: "100%") %>
            <%# <%= cl_image_tag(@list.photo.key, width: 1000, height: 500 ,crop: :thumb, gravity: :face, class: 'card-movie-picture' ) %>
          </div>

          <div class="card-movie-main">
            <div class="card-movie-header">
              <p class="card-movie-title me-3"><%= movie.title %></p>
              <p class="me-2"><%= movie.rating %></p>
              <i class="fa-solid fa-star"></i>
            </div>

            <div class="card-movie-content">
              <p><%= movie.overview %></p>
            </div>

            <div class="card-movie-footer">
              <div class="card-movie-quote">
                <i class="fa-solid fa-quote-left me-2"></i>
                <p><%=  Bookmark.find_by(list: @list, movie: movie).comment %></h5>
              </div>

              <div class="card-movie-delete">
                <%= link_to "edit", edit_bookmark_path(Bookmark.find_by(list: @list, movie: movie)) ,class: "text-primary me-3" %>
                <%= link_to "delete", bookmark_path(movie), data: {turbo_method: "delete", turbo_confirm: "Delete #{movie.title} from #{@list.name}?"} %>
              </div>
            </div>
          </div>

        </div>
      </li>
    <% end %>
  </ul>

  <%= link_to "Back to menu", lists_path %>
</div>